#  clears all objects in "global environment"
rm(list=ls())

DATASET_FILENAME  <- "data/globalterrorismdb_0718dist.csv"          # Name of input dataset file

TYPE_DISCREET     <- "DISCREET"           # field is discreet (numeric)
TYPE_ORDINAL      <- "ORDINAL"            # field is continuous numeric
TYPE_SYMBOLIC     <- "SYMBOLIC"           # field is a string
TYPE_NUMERIC      <- "NUMERIC"            # field is initially a numeric
TYPE_IGNORE       <- "IGNORE"             # field is not encoded

DISCREET_BINS     <- 0                     # Number of empty bins to determine discreet
MAX_LITERALS      <- 55                    # Maximum numner of hotcoding new fields


MYLIBRARIES<-c("outliers",
               "corrplot",
               "MASS",
               "pROC",
               "formattable",
               "stats",
               "caret",
               "PerformanceAnalytics",
               "dplyr")

main<-function(){
  
  main_dataset<-read.csv(DATASET_FILENAME)
  after_1997 <- main_dataset[main_dataset$iyear >= 1997 & main_dataset$doubtterr == 0,]
  
  attacks <- data.frame(
                     "Country" = after_1997$country,
                     "Country_Txt" = after_1997$country_txt,
                     "Region" = after_1997$region_txt,
                     "Attack_Type" = after_1997$attacktype1_txt,
                     "Weapon_Type" = after_1997$weaptype1_txt
  )
  
  encoded<-oneHotEncoding(attacks)
  names(encoded)[names(encoded) == 'Weapon_Type_Vehiclenottoincludevehicleborneexplosivesiecarortruckbombs'] <- 'Weapon_Type_Vehicle_Not_Bomb'
  
} #endof main()

oneHotEncoding <- function (attacks) {
  
  field_types<-NPREPROCESSING_initialFieldType(attacks)
  
  results<-data.frame(field=names(attacks),initial=field_types,types1=field_types)
  print(formattable::formattable(results))
  
  # perform 1 hot encoding on symbolic fields
  catagoricalReadyforML<-NPREPROCESSING_categorical(dataset=attacks,field_types=field_types)
  
  print(formattable::formattable(data.frame(fields=names(catagoricalReadyforML))))
  
  # number of symbolic fields before transformation
  nonNumericbefore<-length(which(field_types==TYPE_SYMBOLIC))
  
  # number of fields generated by 1-hot-encoding
  nonNumerictranformed<-ncol(catagoricalReadyforML)
  print(paste("Before encoding=",nonNumericbefore,"After",nonNumerictranformed))
  
  # Output the names of the encoded fields (literals)
  print(formattable::formattable(data.frame(field=1:nonNumerictranformed,encoded=names(catagoricalReadyforML))))
  
  # The dataset for ML information
  print(paste("Fields=",ncol(catagoricalReadyforML)))
  
  catagoricalReadyforML
}

# ************************************************
# This is where R starts execution

# clears the console area
cat("\014")

library(pacman)
pacman::p_load(char=MYLIBRARIES,install=TRUE,character.only=TRUE)

#Load additional R script files provide for this lab
source("scripts/labFunctions.R")

set.seed(123)

# ************************************************
#main()
print("end")